include: package:very_good_analysis/analysis_options.yaml

formatter:
  page_width: 100

linter:
  rules:
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    sort_constructors_first: false
